# hugo server --minify --themesDir ... --baseURL=http://0.0.0.0:1313/theme/hugo-book/
baseURL: https://elitefantasy.github.io/elitefantasy/


ignoreFiles: [  
    "/content/templates/*",  
    "/content/private/*",
]

# allow you to create a simple menu, based on the section structure of your /content folder
sectionPagesMenu: main

# Book configuration
disablePathToLower: true
enableGitInfo: true

# # Needed for mermaid/katex shortcodes
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 1

# Sidebar menu additional links
menu:
  before:
    # - name: "explore with tags"
    #   url: tags/
    #   weight: 10
    - name: "🔗Github"
      url: "https://github.com/elitefantasy/elitefantasy"
      weight: 90
  # after:
  #   - name: "🔗Github"
  #     url: "https://github.com/elitefantasy/elitefantasy"
  #     weight: 10

params:
  name: Elitefantasy
  title: 🍀 Elitefantasy Digital Garden
  menu1Url: "/elitefantasy"
  menu1Name: "Home"
  menu2Url: "posts/"
  menu2Name: "Posts"
  menu3Url: ""
  menu3Name: ""
  menu4Url: ""
  menu4Name: ""
  menu5Url: ""
  menu5Name: ""

  # OPTIONAL: custom favicon location
  # favicon: 'location/to/favicon.png'

  # whether to display on-hover link preview cards
  enableLinkPreview: true

  # Enable rendering of LaTeX blocks
  # (surrounded by either single or double dollar signs)
  enableLatex: true

  # whether to render titles for code blocks
  enableCodeBlockTitle: true

  # whether to render copy buttons for code blocks
  enableCodeBlockCopy: true

  # whether to render callouts
  enableCallouts: true

  # Show footer, including backlinks and graph view
  enableFooter: false

  # whether backlinks of pages should show the context in which
  # they were mentioned
  enableContextualBacklinks: true

  # whether to show a section of recent notes on the home page
  enableRecentNotes: true

  # Link to your Github repo
  GitHubLink: https://github.com/elitefantasy/elitefantasy

  # Search (WIP)
  search:
    enableSemanticSearch: false
    operandApiKey: "REPLACE-WITH-YOUR-OPERAND-API-KEY"
    operandIndexId: "REPLACE-WITH-YOUR-OPERAND-INDEX-ID"

  # Site description and title
  description:
    Notes, hosted by elitefantasy

  
  # Footer links
  links:
    - link_name: Website
      link: https://github.com/elitefantasy/elitefantasy

  # (Optional, default true) Controls table of contents visibility on right side of pages.
  # Start and end levels can be controlled with markup.tableOfContents setting.
  # You can also specify this parameter per page in front matter.
  BookToC: true

  # (Optional, default none) Set the path to a logo for the book. If the logo is
  # /static/logo.png then the path would be logo.png
  # BookLogo: /logo.png

  # (Optional, default none) Set leaf bundle to render as side menu
  # When not specified file structure and weights will be used
  # BookMenuBundle: /menu

  # (Optional, default docs) Specify root page to render child pages as menu.
  # Page is resoled by .GetPage function: https://gohugo.io/functions/getpage/
  # For backward compatibility you can set '*' to render all sections to menu. Acts same as '/'
  BookSection: "/"

  # Set source repository location.
  # Used for 'Last Modified' and 'Edit this page' links.
  BookRepo: https://github.com/64bitpandas/amethyst

  # Configure the date format used on the pages
  # - In git information
  # - In blog posts
  BookDateFormat: "January 2, 2006"


  # (Optional, default true) Enables comments template on pages
  # By default partals/docs/comments.html includes Disqus template
  # See https://gohugo.io/content-management/comments/#configure-disqus
  # Can be overwritten by same param in page frontmatter
  BookComments: false

  # /!\ This is an experimental feature, might be removed or changed at any time
  # (Optional, experimental, default false) Enables a drop-down menu for translations only if a translation is present.
  BookTranslatedOnly: false

  # Don't change this
  enableSPA: false
  BookSearch: false
  BookServiceWorker: false
  BookPortableLinks: false